name: ptx_env
channels:
  - defaults
dependencies:
  - python=3.10
  - spyder
  - torchaudio
  - torchvision
  - cudatoolkit=10.1
  - notebook
  - matplotlib
  - missingno
  - scipy==1.9.1
  - pandas
  - seaborn
